development:
  adapter: postgresql
  encoding: unicode
  database: nllist_development
  pool: 5
  username: rsj
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: nllist_test
  pool: 5
  username: rsj
  password: 
